##################################################
# Generated by phansible.com
##################################################

#If your Vagrant version is lower than 1.5, you can still use this provisioning
#by commenting or removing the line below and providing the config.vm.box_url parameter,
#if it's not already defined in this Vagrantfile. Keep in mind that you won't be able
#to use the Vagrant Cloud and other newer Vagrant features.
Vagrant.require_version ">= 1.5"

Vagrant.configure("2") do |config|

    config.vm.provider :virtualbox do |v|
        v.name = "hump"
        v.customize [
            "modifyvm", :id,
            "--name", "hump",
            "--memory", 512,
            "--natdnshostresolver1", "on",
            "--cpus", 1,
        ]
    end

    config.vm.box = "ubuntu/trusty64"
    
    config.vm.box_url = "https://vagrantcloud.com/ubuntu/boxes/trusty64/versions/14.04/providers/virtualbox.box"
    
    config.vm.network :private_network, ip: "192.168.20.30", auto_correct: true
    config.ssh.forward_agent = true

    #############################################################
    # Ansible provisioning (you need to have ansible installed)
    #############################################################

    
    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "ansible/playbook.yml"
        ansible.inventory_path = "ansible/inventories/dev"
        ansible.limit = 'all'
        ansible.extra_vars = {
            private_interface: "192.168.20.30",
            hostname: "hump"
        }
    end

      # Check if vagrant-hosts-provisioner plugin is installed
      # Install by running: vagrant plugin install vagrant-hosts-provisioner
      if Vagrant.has_plugin?("vagrant-hosts-provisioner")
        # Run the hostsupdate provisioner
        config.vm.provision :hostsupdate, run: 'always' do |host|
          # Don't include the machine hostname
          host.hostname = false
          # Update the guest machine
          host.manage_guest = true
          # Update the host machine
          host.manage_host = true
          host.aliases = []
          # Pull the hosts entries from the hosts.json file
          host.files = 'hosts.json'
        end
      end
    
    config.vm.synced_folder "./", "/srv/", type: "nfs"
end
