- name: Install php5-fpm
  sudo: yes
  apt: pkg=php5-fpm state=latest

- name: ensure timezone is set in fpm php.ini
  lineinfile: dest=/etc/php5/fpm/php.ini
              regexp='date.timezone ='
              line='date.timezone = {{ timezone }}'
